import { User, Team, Customer, Lead, Deal, Task, Activity, Document as Doc, Payment, Service, Goal } from '@/types';

// ==================== TEAM & USERS ====================
export const mockTeam: Team = {
    id: 'team-001', name: 'LeadSpark Team', plan: 'team', created_at: '2025-01-15T00:00:00Z',
};

export const mockUsers: User[] = [
    { id: 'user-001', email: 'asia@leadspark.co', name: 'Asia', avatar_url: null, role: 'admin', team_id: 'team-001', created_at: '2025-01-15T00:00:00Z' },
    { id: 'user-002', email: 'som@leadspark.co', name: 'Som', avatar_url: null, role: 'member', team_id: 'team-001', created_at: '2025-02-01T00:00:00Z' },
];

// ==================== CUSTOMERS (20) ====================
export const mockCustomers: Customer[] = [
    { id: 'cust-001', team_id: 'team-001', business_name: 'คาเฟ่ลุมพินี', industry: 'ร้านอาหาร/คาเฟ่', address: '123 ถ.สีลม แขวงสีลม เขตบางรัก กรุงเทพฯ 10500', phone: '02-234-5678', email: 'lumpini@cafe.co.th', line_id: '@lumpini_cafe', website_url: 'https://lumpinicafe.co.th', facebook_url: 'https://fb.com/lumpinicafe', google_maps_url: '', google_rating: 4.5, google_review_count: 128, contact_person_name: 'สมชาย วงษ์สุวรรณ', contact_person_position: 'เจ้าของร้าน', contact_person_phone: '081-234-5678', contact_person_email: 'somchai@cafe.co.th', secondary_contact_name: 'สมหญิง วงษ์สุวรรณ', secondary_contact_phone: '082-345-6789', important_notes: 'ลูกค้าชอบบริการที่รวดเร็ว ต้องการระบบ POS ใหม่ช่วงไตรมาส 2', status: 'active', is_pinned: true, assigned_to: 'user-001', source: 'lead_search', tags: ['VIP', 'คาเฟ่'], created_at: '2025-06-01T00:00:00Z', updated_at: '2026-02-15T00:00:00Z' },
    { id: 'cust-002', team_id: 'team-001', business_name: 'คลินิกหมอลี', industry: 'คลินิก/สปา', address: '45/2 ซ.สุขุมวิท 31 แขวงคลองตันเหนือ เขตวัฒนา กรุงเทพฯ 10110', phone: '02-662-7890', email: 'drlee@clinic.co.th', line_id: '@drlee_clinic', website_url: '', facebook_url: 'https://fb.com/drleeclinic', google_maps_url: '', google_rating: 4.8, google_review_count: 256, contact_person_name: 'นพ.ลี สมบูรณ์', contact_person_position: 'แพทย์ผู้อำนวยการ', contact_person_phone: '089-876-5432', contact_person_email: 'dr.lee@clinic.co.th', secondary_contact_name: 'คุณแนน', secondary_contact_phone: '089-111-2222', important_notes: 'สนใจระบบจองคิวออนไลน์ งบประมาณ 50K-80K', status: 'active', is_pinned: true, assigned_to: 'user-001', source: 'manual', tags: ['สุขภาพ', 'งบสูง'], created_at: '2025-07-15T00:00:00Z', updated_at: '2026-02-10T00:00:00Z' },
    { id: 'cust-003', team_id: 'team-001', business_name: 'โรงแรมริเวอร์ไซด์', industry: 'โรงแรม', address: '88 ถ.เจริญกรุง เขตบางคอแหลม กรุงเทพฯ 10120', phone: '02-861-1234', email: 'info@riverside.co.th', line_id: '@riverside_bkk', website_url: 'https://riverside-bkk.com', facebook_url: 'https://fb.com/riversidebkk', google_maps_url: '', google_rating: 4.2, google_review_count: 89, contact_person_name: 'คุณวิภา จันทร์แจ่ม', contact_person_position: 'ผู้จัดการทั่วไป', contact_person_phone: '085-432-1098', contact_person_email: 'wipa@riverside.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'ต้องการเว็บไซต์ใหม่ที่รองรับการจอง', status: 'active', is_pinned: true, assigned_to: 'user-002', source: 'lead_search', tags: ['โรงแรม', 'เว็บไซต์'], created_at: '2025-08-01T00:00:00Z', updated_at: '2026-02-12T00:00:00Z' },
    { id: 'cust-004', team_id: 'team-001', business_name: 'ฟิตเนส พาวเวอร์ยิม', industry: 'ฟิตเนส', address: '12 ซ.รัชดาภิเษก 7 เขตดินแดง กรุงเทพฯ 10400', phone: '02-275-9900', email: 'info@powergym.co.th', line_id: '@powergym', website_url: 'https://powergym.co.th', facebook_url: 'https://fb.com/powergymbkk', google_maps_url: '', google_rating: 4.1, google_review_count: 67, contact_person_name: 'คุณธนา พลศิริ', contact_person_position: 'เจ้าของ', contact_person_phone: '091-234-5678', contact_person_email: 'thana@powergym.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'สนใจแอปสำหรับสมาชิก ต้องการเริ่มเดือนหน้า', status: 'active', is_pinned: true, assigned_to: 'user-001', source: 'referral', tags: ['ฟิตเนส', 'แอป'], created_at: '2025-09-01T00:00:00Z', updated_at: '2026-02-14T00:00:00Z' },
    { id: 'cust-005', team_id: 'team-001', business_name: 'ร้านข้าวแกงป้าแจ๋ว', industry: 'ร้านอาหาร/คาเฟ่', address: '67 ถ.ลาดพร้าว แขวงจอมพล เขตจตุจักร กรุงเทพฯ 10900', phone: '02-513-4567', email: '', line_id: '', website_url: '', facebook_url: 'https://fb.com/pajaew', google_maps_url: '', google_rating: 4.6, google_review_count: 312, contact_person_name: 'ป้าแจ๋ว', contact_person_position: 'เจ้าของ', contact_person_phone: '086-543-2109', contact_person_email: '', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'ร้านเล็ก งบน้อย สนใจ LINE OA อย่างเดียว', status: 'active', is_pinned: false, assigned_to: 'user-002', source: 'lead_search', tags: ['ร้านอาหาร', 'งบน้อย'], created_at: '2025-09-15T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
    { id: 'cust-006', team_id: 'team-001', business_name: 'สปา เดอ สยาม', industry: 'คลินิก/สปา', address: '99 ถ.สาทร แขวงยานนาวา เขตสาทร กรุงเทพฯ 10120', phone: '02-287-6543', email: 'contact@spadesiam.com', line_id: '@spadesiam', website_url: 'https://spadesiam.com', facebook_url: 'https://fb.com/spadesiam', google_maps_url: '', google_rating: 4.7, google_review_count: 189, contact_person_name: 'คุณนิดา สุขสมบูรณ์', contact_person_position: 'ผู้จัดการ', contact_person_phone: '092-111-3344', contact_person_email: 'nida@spadesiam.com', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'ต้องการระบบจองออนไลน์ พร้อมโปรโมชั่น', status: 'pending_delivery', is_pinned: false, assigned_to: 'user-001', source: 'manual', tags: ['สปา', 'จองออนไลน์'], created_at: '2025-10-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' },
    { id: 'cust-007', team_id: 'team-001', business_name: 'โรงเรียนสอนภาษา ABC', industry: 'การศึกษา', address: '234 ถ.อารีย์ แขวงพญาไท เขตพญาไท กรุงเทพฯ 10400', phone: '02-270-1111', email: 'info@abclang.co.th', line_id: '@abclang', website_url: 'https://abclang.co.th', facebook_url: '', google_maps_url: '', google_rating: 4.3, google_review_count: 45, contact_person_name: 'ครูเจน', contact_person_position: 'ผู้อำนวยการ', contact_person_phone: '083-222-3333', contact_person_email: 'jane@abclang.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'สนใจระบบลงทะเบียนเรียนออนไลน์', status: 'active', is_pinned: false, assigned_to: 'user-002', source: 'lead_search', tags: ['การศึกษา'], created_at: '2025-10-15T00:00:00Z', updated_at: '2026-01-25T00:00:00Z' },
    { id: 'cust-008', team_id: 'team-001', business_name: 'ร้านกาแฟ Brew House', industry: 'ร้านอาหาร/คาเฟ่', address: '55 ซ.ทองหล่อ 13 เขตวัฒนา กรุงเทพฯ 10110', phone: '02-381-9876', email: 'hello@brewhouse.co', line_id: '@brewhouse', website_url: 'https://brewhouse.co', facebook_url: 'https://fb.com/brewhouse', google_maps_url: '', google_rating: 4.4, google_review_count: 204, contact_person_name: 'คุณบีม', contact_person_position: 'เจ้าของ', contact_person_phone: '094-567-8901', contact_person_email: 'beam@brewhouse.co', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'สนใจระบบสั่งอาหารออนไลน์', status: 'overdue_payment', is_pinned: false, assigned_to: 'user-001', source: 'referral', tags: ['คาเฟ่', 'เกินกำหนด'], created_at: '2025-11-01T00:00:00Z', updated_at: '2026-02-10T00:00:00Z' },
    { id: 'cust-009', team_id: 'team-001', business_name: 'บริษัท ดิจิตอลเวิร์ค จำกัด', industry: 'สำนักงาน', address: '789 อาคาร One City Centre ถ.เพลินจิต กรุงเทพฯ 10330', phone: '02-655-0000', email: 'contact@digitalwork.co.th', line_id: '', website_url: 'https://digitalwork.co.th', facebook_url: '', google_maps_url: '', google_rating: 0, google_review_count: 0, contact_person_name: 'คุณแม็ค', contact_person_position: 'CEO', contact_person_phone: '081-999-0000', contact_person_email: 'mac@digitalwork.co.th', secondary_contact_name: 'คุณนุ่น', secondary_contact_phone: '081-888-7777', important_notes: 'บริษัทใหญ่ งบประมาณ 200K+ ต้องการ CRM', status: 'active', is_pinned: false, assigned_to: 'user-001', source: 'manual', tags: ['B2B', 'งบสูง'], created_at: '2025-11-15T00:00:00Z', updated_at: '2026-02-05T00:00:00Z' },
    { id: 'cust-010', team_id: 'team-001', business_name: 'ร้านค้าออนไลน์ ShopDee', industry: 'ค้าปลีก', address: '321 ถ.พระราม 9 เขตห้วยขวาง กรุงเทพฯ 10310', phone: '02-248-9999', email: 'admin@shopdee.com', line_id: '@shopdee', website_url: 'https://shopdee.com', facebook_url: 'https://fb.com/shopdee', google_maps_url: '', google_rating: 3.9, google_review_count: 56, contact_person_name: 'คุณตาล', contact_person_position: 'ผู้จัดการ', contact_person_phone: '095-678-1234', contact_person_email: 'tarn@shopdee.com', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'ต้องการปรับปรุงเว็บไซต์ E-commerce', status: 'active', is_pinned: false, assigned_to: 'user-002', source: 'lead_search', tags: ['E-commerce', 'ค้าปลีก'], created_at: '2025-12-01T00:00:00Z', updated_at: '2026-01-30T00:00:00Z' },
    { id: 'cust-011', team_id: 'team-001', business_name: 'คลินิกทันตกรรม ฟันสวย', industry: 'คลินิก/สปา', address: '77 ถ.เอกมัย แขวงคลองตันเหนือ เขตวัฒนา กรุงเทพฯ 10110', phone: '02-392-5555', email: 'info@funsuay.co.th', line_id: '@funsuay', website_url: '', facebook_url: 'https://fb.com/funsuay', google_maps_url: '', google_rating: 4.9, google_review_count: 340, contact_person_name: 'ทพ.สุวิทย์', contact_person_position: 'ทันตแพทย์', contact_person_phone: '087-654-3210', contact_person_email: 'suwit@funsuay.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: '', status: 'active', is_pinned: false, assigned_to: 'user-001', source: 'referral', tags: ['ทันตกรรม'], created_at: '2025-12-15T00:00:00Z', updated_at: '2026-01-28T00:00:00Z' },
    { id: 'cust-012', team_id: 'team-001', business_name: 'โยคะสตูดิโอ OM', industry: 'ฟิตเนส', address: '33 ซ.สุขุมวิท 49 เขตวัฒนา กรุงเทพฯ 10110', phone: '02-662-4444', email: 'om@yogaom.co.th', line_id: '@yogaom', website_url: '', facebook_url: 'https://fb.com/yogaom', google_maps_url: '', google_rating: 4.6, google_review_count: 78, contact_person_name: 'ครูนก', contact_person_position: 'ผู้ก่อตั้ง', contact_person_phone: '088-123-4567', contact_person_email: 'nok@yogaom.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: '', status: 'inactive', is_pinned: false, assigned_to: 'user-002', source: 'lead_search', tags: ['โยคะ'], created_at: '2025-06-01T00:00:00Z', updated_at: '2025-11-15T00:00:00Z' },
    { id: 'cust-013', team_id: 'team-001', business_name: 'ร้านอาหารญี่ปุ่น ซากุระ', industry: 'ร้านอาหาร/คาเฟ่', address: '199 ถ.สุขุมวิท 55 (ทองหล่อ) กรุงเทพฯ 10110', phone: '02-714-8888', email: 'sakura@jpfood.co.th', line_id: '@sakura_jp', website_url: 'https://sakura-jp.co.th', facebook_url: '', google_maps_url: '', google_rating: 4.3, google_review_count: 167, contact_person_name: 'คุณยูกิ', contact_person_position: 'ผู้จัดการ', contact_person_phone: '093-456-7890', contact_person_email: 'yuki@jpfood.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'ต้องการเมนูออนไลน์ QR Code', status: 'active', is_pinned: false, assigned_to: 'user-001', source: 'manual', tags: ['ร้านอาหาร', 'ญี่ปุ่น'], created_at: '2026-01-05T00:00:00Z', updated_at: '2026-02-10T00:00:00Z' },
    { id: 'cust-014', team_id: 'team-001', business_name: 'โรงแรม เดอะ บลูม', industry: 'โรงแรม', address: '456 ถ.สุรวงศ์ เขตบางรัก กรุงเทพฯ 10500', phone: '02-235-7777', email: 'info@thebloom.co.th', line_id: '@thebloom', website_url: 'https://thebloom.co.th', facebook_url: 'https://fb.com/thebloomhotel', google_maps_url: '', google_rating: 4.0, google_review_count: 95, contact_person_name: 'คุณภัทรา', contact_person_position: 'Sales Director', contact_person_phone: '081-555-6666', contact_person_email: 'pattra@thebloom.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: '', status: 'pending_delivery', is_pinned: false, assigned_to: 'user-002', source: 'lead_search', tags: ['โรงแรม'], created_at: '2026-01-10T00:00:00Z', updated_at: '2026-02-08T00:00:00Z' },
    { id: 'cust-015', team_id: 'team-001', business_name: 'ร้านเสริมสวย นัมเบอร์วัน', industry: 'คลินิก/สปา', address: '28 ซ.อารีย์สัมพันธ์ เขตพญาไท กรุงเทพฯ 10400', phone: '02-279-3333', email: '', line_id: '@no1beauty', website_url: '', facebook_url: 'https://fb.com/no1beauty', google_maps_url: '', google_rating: 4.1, google_review_count: 42, contact_person_name: 'คุณแอน', contact_person_position: 'เจ้าของ', contact_person_phone: '086-777-8888', contact_person_email: '', secondary_contact_name: '', secondary_contact_phone: '', important_notes: '', status: 'active', is_pinned: false, assigned_to: 'user-001', source: 'referral', tags: ['เสริมสวย'], created_at: '2026-01-20T00:00:00Z', updated_at: '2026-02-05T00:00:00Z' },
    { id: 'cust-016', team_id: 'team-001', business_name: 'สำนักงานบัญชี AAA', industry: 'สำนักงาน', address: '567 อาคารสาทรซิตี้ ถ.สาทรเหนือ กรุงเทพฯ 10500', phone: '02-636-2222', email: 'info@aaa-acc.co.th', line_id: '', website_url: 'https://aaa-acc.co.th', facebook_url: '', google_maps_url: '', google_rating: 3.5, google_review_count: 12, contact_person_name: 'คุณอ้อ', contact_person_position: 'ผู้จัดการ', contact_person_phone: '089-333-4444', contact_person_email: 'aor@aaa-acc.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: '', status: 'overdue_payment', is_pinned: false, assigned_to: 'user-002', source: 'manual', tags: ['บัญชี'], created_at: '2025-08-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' },
    { id: 'cust-017', team_id: 'team-001', business_name: 'ร้านขนม Sweet Moment', industry: 'ร้านอาหาร/คาเฟ่', address: '88/5 ซ.ลาดพร้าว 71 เขตลาดพร้าว กรุงเทพฯ 10230', phone: '02-539-1234', email: 'sweet@moment.co.th', line_id: '@sweetmoment', website_url: '', facebook_url: 'https://fb.com/sweetmoment', google_maps_url: '', google_rating: 4.7, google_review_count: 256, contact_person_name: 'คุณมิ้นท์', contact_person_position: 'เจ้าของ', contact_person_phone: '097-888-9999', contact_person_email: 'mint@moment.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'สนใจทำเว็บสั่งเค้กออนไลน์', status: 'active', is_pinned: false, assigned_to: 'user-001', source: 'lead_search', tags: ['ขนม', 'ออนไลน์'], created_at: '2026-01-25T00:00:00Z', updated_at: '2026-02-12T00:00:00Z' },
    { id: 'cust-018', team_id: 'team-001', business_name: 'โรงเรียนดนตรี Do Re Mi', industry: 'การศึกษา', address: '15 ซ.เอกมัย 10 เขตวัฒนา กรุงเทพฯ 10110', phone: '02-381-5555', email: 'doremi@music.co.th', line_id: '@doremimusic', website_url: '', facebook_url: 'https://fb.com/doremimusic', google_maps_url: '', google_rating: 4.5, google_review_count: 88, contact_person_name: 'ครูเปียโน', contact_person_position: 'ผู้อำนวยการ', contact_person_phone: '084-111-2222', contact_person_email: 'piano@music.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: '', status: 'active', is_pinned: false, assigned_to: 'user-002', source: 'referral', tags: ['ดนตรี', 'การศึกษา'], created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-14T00:00:00Z' },
    { id: 'cust-019', team_id: 'team-001', business_name: 'ร้านกระเป๋า Bagster', industry: 'ค้าปลีก', address: '234 ถ.สยามสแควร์ ซ.3 เขตปทุมวัน กรุงเทพฯ 10330', phone: '02-251-8888', email: 'hello@bagster.co.th', line_id: '@bagster', website_url: 'https://bagster.co.th', facebook_url: 'https://fb.com/bagster', google_maps_url: '', google_rating: 4.2, google_review_count: 134, contact_person_name: 'คุณฝ้าย', contact_person_position: 'เจ้าของ', contact_person_phone: '091-444-5555', contact_person_email: 'fai@bagster.co.th', secondary_contact_name: '', secondary_contact_phone: '', important_notes: '', status: 'inactive', is_pinned: false, assigned_to: 'user-001', source: 'lead_search', tags: ['ค้าปลีก'], created_at: '2025-07-01T00:00:00Z', updated_at: '2025-12-01T00:00:00Z' },
    { id: 'cust-020', team_id: 'team-001', business_name: 'ฟิตเนส CrossFit BKK', industry: 'ฟิตเนส', address: '90 ซ.สุขุมวิท 39 เขตวัฒนา กรุงเทพฯ 10110', phone: '02-662-9900', email: 'info@crossfitbkk.com', line_id: '@crossfitbkk', website_url: 'https://crossfitbkk.com', facebook_url: 'https://fb.com/crossfitbkk', google_maps_url: '', google_rating: 4.4, google_review_count: 201, contact_person_name: 'โค้ชเจมส์', contact_person_position: 'เจ้าของ', contact_person_phone: '092-333-4444', contact_person_email: 'james@crossfitbkk.com', secondary_contact_name: '', secondary_contact_phone: '', important_notes: 'ต้องการแอปจองคลาสสำหรับสมาชิก', status: 'active', is_pinned: false, assigned_to: 'user-002', source: 'manual', tags: ['ฟิตเนส', 'แอป'], created_at: '2026-02-05T00:00:00Z', updated_at: '2026-02-15T00:00:00Z' },
];
