import { BusinessProfile, RFQ, Proposal, MarketplaceDeal } from '@/types';

// ==================== MY BUSINESS PROFILE ====================

export const MY_BUSINESS_PROFILE: BusinessProfile = {
    id: 'bp-my',
    userId: 'user-1',
    businessName: 'LeadSpark Digital',
    businessType: 'service',
    categories: ['ไอที/เทคโนโลยี'],
    subCategories: ['ออกแบบเว็บไซต์', 'Digital Marketing', 'SEO'],
    province: 'กรุงเทพมหานคร',
    district: 'วัฒนา',
    description: 'เราให้บริการออกแบบเว็บไซต์ ทำ SEO และ Digital Marketing ครบวงจร เน้นธุรกิจ SME ไทย มีประสบการณ์มากกว่า 5 ปี ผลงานกว่า 200+ โปรเจกต์',
    products: [
        {
            id: 'p-1',
            name: 'ออกแบบและพัฒนาเว็บไซต์',
            description: 'เว็บไซต์ธุรกิจระดับมืออาชีพ รองรับมือถือ โหลดเร็ว SEO friendly',
            startingPrice: 15000,
            moq: 1,
            leadTime: '14-21 วัน',
            tags: ['เว็บไซต์', 'WordPress', 'React', 'SEO'],
            images: [],
        },
        {
            id: 'p-2',
            name: 'บริการ SEO รายเดือน',
            description: 'เพิ่มอันดับ Google ด้วยเทคนิค White Hat SEO รายงานทุกเดือน',
            startingPrice: 8000,
            moq: 3,
            leadTime: 'รายเดือน',
            tags: ['SEO', 'Google', 'Keyword', 'Backlink'],
            images: [],
        },
        {
            id: 'p-3',
            name: 'จัดการ Social Media',
            description: 'ดูแล Facebook, Instagram, TikTok คอนเทนต์ครบ กราฟิกสวยงาม',
            startingPrice: 12000,
            moq: 3,
            leadTime: 'รายเดือน',
            tags: ['Facebook', 'Instagram', 'Content', 'Ads'],
            images: [],
        },
    ],
    buyingNeeds: [
        {
            id: 'bn-1',
            name: 'ถ่ายภาพสินค้าและ Portfolio',
            category: 'ถ่ายภาพ/วิดีโอ',
            description: 'ต้องการช่างภาพมืออาชีพถ่าย Portfolio ผลงาน และรูปทีมงาน',
            frequency: 'occasional',
        },
        {
            id: 'bn-2',
            name: 'เขียนบทความ/Content',
            category: 'คอนเทนต์',
            description: 'นักเขียนบทความ SEO ภาษาไทย เน้นธุรกิจ ไอที และการตลาด',
            frequency: 'regular',
        },
        {
            id: 'bn-3',
            name: 'พิมพ์สื่อสิ่งพิมพ์',
            category: 'สิ่งพิมพ์',
            description: 'นามบัตร โบรชัวร์ Flyer สำหรับงาน Event และการตลาด',
            frequency: 'occasional',
        },
    ],
    trustLevel: 3,
    rating: 4.6,
    reviewCount: 23,
    dealsCompleted: 18,
    responseRate: 92,
    avgResponseTime: '2 ชั่วโมง',
    portfolioImages: [],
    contactPhone: '081-234-5678',
    contactEmail: 'hello@leadspark.digital',
    lineId: '@leadspark',
    website: 'www.leadspark.digital',
    verified: true,
    memberSince: '2024-01-15',
    matchPowerScore: 78,
};

// ==================== OTHER BUSINESS PROFILES ====================

export const BUSINESS_PROFILES: BusinessProfile[] = [
    {
        id: 'bp-1',
        userId: 'user-2',
        businessName: 'โรงพิมพ์ศรีสยาม',
        businessType: 'manufacturer',
        categories: ['สิ่งพิมพ์'],
        subCategories: ['นามบัตร', 'โบรชัวร์', 'แบนเนอร์', 'สติกเกอร์'],
        province: 'กรุงเทพมหานคร',
        district: 'มีนบุรี',
        description: 'โรงพิมพ์ครบวงจร ผลิตสิ่งพิมพ์ทุกชนิด คุณภาพดี ราคาถูก ส่งทั่วไทย',
        products: [
            { id: 'p-bp1-1', name: 'นามบัตร (500 ใบ)', description: 'กระดาษ 350g เคลือบด้าน/มัน', startingPrice: 350, moq: 500, leadTime: '3-5 วัน', tags: ['นามบัตร', 'พิมพ์'], images: [] },
            { id: 'p-bp1-2', name: 'โบรชัวร์ A4 (500 ใบ)', description: 'อาร์ตการ์ด 150g พิมพ์ 4 สี', startingPrice: 1500, moq: 500, leadTime: '5-7 วัน', tags: ['โบรชัวร์', 'A4'], images: [] },
        ],
        buyingNeeds: [
            { id: 'bn-bp1-1', name: 'บริการ Digital Marketing', category: 'ไอที/การตลาด', description: 'ต้องการทำตลาดออนไลน์เพิ่ม', frequency: 'regular' },
        ],
        trustLevel: 3,
        rating: 4.8,
        reviewCount: 47,
        dealsCompleted: 89,
        responseRate: 97,
        avgResponseTime: '30 นาที',
        portfolioImages: [],
        contactPhone: '02-123-4567',
        contactEmail: 'info@srisayamprint.com',
        lineId: '@srisayam',
        website: 'www.srisayamprint.com',
        verified: true,
        memberSince: '2023-06-01',
        matchPowerScore: 91,
    },
    {
        id: 'bp-2',
        userId: 'user-3',
        businessName: 'ร้านป้ายไฟ LED สมชาย',
        businessType: 'manufacturer',
        categories: ['โฆษณา/ป้าย'],
        subCategories: ['ป้ายไฟ LED', 'ป้ายกล่องไฟ', 'ป้ายอะคริลิค'],
        province: 'นนทบุรี',
        district: 'บางใหญ่',
        description: 'ผลิตป้ายไฟ LED ป้ายกล่องไฟ ป้ายอะคริลิค ทุกขนาด รับประกัน 2 ปี ติดตั้งทั่ว กทม.',
        products: [
            { id: 'p-bp2-1', name: 'ป้ายไฟ LED ตัวอักษร', description: 'กว้าง 1 เมตร สว่าง คงทน', startingPrice: 3500, moq: 1, leadTime: '7-10 วัน', tags: ['LED', 'ป้าย', 'ไฟ'], images: [] },
            { id: 'p-bp2-2', name: 'ป้ายกล่องไฟ', description: 'อะคริลิคขาวพ่นสี ไฟ LED ภายใน', startingPrice: 5500, moq: 1, leadTime: '10-14 วัน', tags: ['กล่องไฟ', 'อะคริลิค'], images: [] },
        ],
        buyingNeeds: [
            { id: 'bn-bp2-1', name: 'ออกแบบกราฟิก', category: 'กราฟิก/ดีไซน์', description: 'นักออกแบบสำหรับ artwork ป้าย', frequency: 'regular' },
        ],
        trustLevel: 2,
        rating: 4.5,
        reviewCount: 31,
        dealsCompleted: 52,
        responseRate: 88,
        avgResponseTime: '1 ชั่วโมง',
        portfolioImages: [],
        contactPhone: '081-987-6543',
        contactEmail: 'somchai.led@gmail.com',
        lineId: 'somchai_led',
        website: '',
        verified: true,
        memberSince: '2023-11-20',
        matchPowerScore: 72,
    },
    {
        id: 'bp-3',
        userId: 'user-4',
        businessName: 'ABC Catering & Events',
        businessType: 'service',
        categories: ['อาหาร/เครื่องดื่ม'],
        subCategories: ['จัดเลี้ยง', 'บุฟเฟ่ต์', 'Coffee Break'],
        province: 'กรุงเทพมหานคร',
        district: 'ลาดพร้าว',
        description: 'บริการจัดเลี้ยงงานสัมมนา ประชุม กาล่าดินเนอร์ งานแต่งงาน ทีมเชฟมืออาชีพ',
        products: [
            { id: 'p-bp3-1', name: 'Coffee Break Package', description: 'ขนม เครื่องดื่ม สำหรับ 50 คน', startingPrice: 8500, moq: 30, leadTime: '3 วัน', tags: ['coffee', 'บุฟเฟ่ต์'], images: [] },
            { id: 'p-bp3-2', name: 'บุฟเฟ่ต์อาหารไทย', description: 'อาหารไทยหลากหลาย 15-20 เมนู', startingPrice: 350, moq: 50, leadTime: '5 วัน', tags: ['อาหาร', 'ไทย'], images: [] },
        ],
        buyingNeeds: [
            { id: 'bn-bp3-1', name: 'วัสดุบรรจุภัณฑ์', category: 'บรรจุภัณฑ์', description: 'กล่องอาหาร ถ้วย ช้อนส้อม ประจำเดือน', frequency: 'regular' },
            { id: 'bn-bp3-2', name: 'เว็บไซต์และ Social Media', category: 'ไอที/การตลาด', description: 'ต้องการ เว็บไซต์ ใหม่ และดูแล Facebook/IG', frequency: 'onetime' },
        ],
        trustLevel: 3,
        rating: 4.7,
        reviewCount: 68,
        dealsCompleted: 143,
        responseRate: 95,
        avgResponseTime: '45 นาที',
        portfolioImages: [],
        contactPhone: '02-555-7890',
        contactEmail: 'abc.catering@gmail.com',
        lineId: '@abccatering',
        website: 'www.abccatering.co.th',
        verified: true,
        memberSince: '2023-03-10',
        matchPowerScore: 85,
    },
    {
        id: 'bp-4',
        userId: 'user-5',
        businessName: 'สำนักงานบัญชี ธนกิจ',
        businessType: 'service',
        categories: ['การเงิน/บัญชี'],
        subCategories: ['ทำบัญชี', 'ยื่นภาษี', 'ตรวจสอบบัญชี', 'จดทะเบียนบริษัท'],
        province: 'กรุงเทพมหานคร',
        district: 'ห้วยขวาง',
        description: 'สำนักงานบัญชีครบวงจร ทำบัญชี ยื่นภาษี ตรวจสอบงบ จดทะเบียนบริษัท ราคาเป็นธรรม',
        products: [
            { id: 'p-bp4-1', name: 'บริการทำบัญชีรายเดือน', description: 'บัญชีครบ ภาษีมูลค่าเพิ่ม ประกันสังคม', startingPrice: 2500, moq: 3, leadTime: 'รายเดือน', tags: ['บัญชี', 'ภาษี', 'VAT'], images: [] },
            { id: 'p-bp4-2', name: 'จดทะเบียนบริษัท', description: 'ครบทุกขั้นตอน พร้อมเอกสาร 45 วัน', startingPrice: 7000, moq: 1, leadTime: '30-45 วัน', tags: ['จดทะเบียน', 'บริษัท'], images: [] },
        ],
        buyingNeeds: [
            { id: 'bn-bp4-1', name: 'โปรแกรมบัญชี/Software', category: 'ไอที/Software', description: 'ซอฟต์แวร์บัญชีสำหรับลูกค้า SME', frequency: 'occasional' },
            { id: 'bn-bp4-2', name: 'เว็บไซต์สำนักงาน', category: 'ไอที/เว็บไซต์', description: 'เว็บไซต์แนะนำบริการ SEO ดี', frequency: 'onetime' },
        ],
        trustLevel: 4,
        rating: 4.9,
        reviewCount: 112,
        dealsCompleted: 280,
        responseRate: 99,
        avgResponseTime: '20 นาที',
        portfolioImages: [],
        contactPhone: '02-888-1234',
        contactEmail: 'thanakij.acc@gmail.com',
        lineId: '@thanakijacc',
        website: 'www.thanakijacc.com',
        verified: true,
        memberSince: '2022-09-01',
        matchPowerScore: 95,
    },
    {
        id: 'bp-5',
        userId: 'user-6',
        businessName: 'Fashion Plus โรงงานเสื้อผ้า',
        businessType: 'manufacturer',
        categories: ['สิ่งทอ/เสื้อผ้า'],
        subCategories: ['เสื้อโปโล', 'ยูนิฟอร์ม', 'เสื้อ Event', 'เสื้อผ้าแฟชั่น'],
        province: 'สมุทรปราการ',
        district: 'บางพลี',
        description: 'โรงงานเสื้อผ้า OEM รับผลิตตามแบบ เสื้อยืด โปโล ยูนิฟอร์ม MOQ ต่ำ คุณภาพสูง',
        products: [
            { id: 'p-bp5-1', name: 'เสื้อโปโลสั่งทำ', description: 'ปักโลโก้ได้ เลือกสีได้ MOQ 50 ตัว', startingPrice: 180, moq: 50, leadTime: '14-21 วัน', tags: ['โปโล', 'ยูนิฟอร์ม', 'ปักโลโก้'], images: [] },
            { id: 'p-bp5-2', name: 'เสื้อ Event', description: 'เสื้อ Dry-Fit สกรีนได้ MOQ 100 ตัว', startingPrice: 120, moq: 100, leadTime: '10-14 วัน', tags: ['Event', 'สกรีน', 'Dry-Fit'], images: [] },
        ],
        buyingNeeds: [
            { id: 'bn-bp5-1', name: 'ผ้าเนื้อดีราคาส่ง', category: 'วัตถุดิบ/ผ้า', description: 'ผ้า Pique, Dry-Fit, Cotton ปริมาณมาก', frequency: 'regular' },
            { id: 'bn-bp5-2', name: 'ถ่ายภาพสินค้า', category: 'ถ่ายภาพ', description: 'ถ่ายแคตตาล็อกเสื้อผ้า Lookbook', frequency: 'occasional' },
            { id: 'bn-bp5-3', name: 'เว็บไซต์ E-commerce', category: 'ไอที/เว็บ', description: 'เว็บสั่งซื้อออนไลน์สำหรับ B2B', frequency: 'onetime' },
        ],
        trustLevel: 3,
        rating: 4.6,
        reviewCount: 89,
        dealsCompleted: 234,
        responseRate: 91,
        avgResponseTime: '3 ชั่วโมง',
        portfolioImages: [],
        contactPhone: '02-700-1234',
        contactEmail: 'fashionplus.factory@gmail.com',
        lineId: '@fashionplusfactory',
        website: '',
        verified: true,
        memberSince: '2023-02-15',
        matchPowerScore: 80,
    },
    {
        id: 'bp-6',
        userId: 'user-7',
        businessName: 'ส่งด่วน Express Logistics',
        businessType: 'service',
        categories: ['ขนส่ง/โลจิสติกส์'],
        subCategories: ['ขนส่งด่วน', 'ขนส่งสินค้า', 'รถรับจ้าง'],
        province: 'กรุงเทพมหานคร',
        district: 'สาทร',
        description: 'บริการขนส่งสินค้าด่วน รถกระบะ รถ6ล้อ รับ-ส่งทั่ว กทม. และปริมณฑล Same Day Delivery',
        products: [
            { id: 'p-bp6-1', name: 'รถกระบะส่งสินค้า (Same Day)', description: 'ส่งใน กทม. ภายใน 3 ชั่วโมง', startingPrice: 400, moq: 1, leadTime: 'Same Day', tags: ['กระบะ', 'ด่วน', 'Same Day'], images: [] },
            { id: 'p-bp6-2', name: 'รถ6ล้อ (รายวัน)', description: 'รับสินค้าหนัก ส่งต่างจังหวัด', startingPrice: 3500, moq: 1, leadTime: '1-2 วัน', tags: ['6ล้อ', 'ต่างจังหวัด'], images: [] },
        ],
        buyingNeeds: [
            { id: 'bn-bp6-1', name: 'ระบบ GPS Tracking', category: 'ไอที/Software', description: 'ซอฟต์แวร์ติดตามรถขนส่ง', frequency: 'onetime' },
            { id: 'bn-bp6-2', name: 'ประกันภัยสินค้า', category: 'การเงิน/ประกัน', description: 'ประกันสินค้าระหว่างขนส่ง', frequency: 'regular' },
        ],
        trustLevel: 2,
        rating: 4.3,
        reviewCount: 156,
        dealsCompleted: 1240,
        responseRate: 85,
        avgResponseTime: '15 นาที',
        portfolioImages: [],
        contactPhone: '092-345-6789',
        contactEmail: 'songduan.express@gmail.com',
        lineId: '@songduan',
        website: '',
        verified: false,
        memberSince: '2024-03-01',
        matchPowerScore: 62,
    },
    {
        id: 'bp-7',
        userId: 'user-8',
        businessName: 'IT Solution Pro',
        businessType: 'service',
        categories: ['ไอที/เทคโนโลยี'],
        subCategories: ['พัฒนา Software', 'ERP', 'ระบบ POS', 'Cloud Solutions'],
        province: 'กรุงเทพมหานคร',
        district: 'จตุจักร',
        description: 'พัฒนาซอฟต์แวร์ธุรกิจ ระบบ ERP, POS, CRM ครบวงจร ประสบการณ์ 10+ ปี ลูกค้า 200+ ราย',
        products: [
            { id: 'p-bp7-1', name: 'ระบบ POS สำหรับร้านค้า', description: 'POS ครบฟีเจอร์ รองรับบัตรเครดิต/QR', startingPrice: 25000, moq: 1, leadTime: '30-45 วัน', tags: ['POS', 'ร้านค้า', 'ซอฟต์แวร์'], images: [] },
            { id: 'p-bp7-2', name: 'พัฒนาแอปมือถือ', description: 'iOS + Android ต่อ Package', startingPrice: 150000, moq: 1, leadTime: '60-90 วัน', tags: ['App', 'iOS', 'Android'], images: [] },
        ],
        buyingNeeds: [
            { id: 'bn-bp7-1', name: 'นักพัฒนา Freelance', category: 'ไอที/Freelance', description: 'Frontend developer (React/Vue) สำหรับโปรเจกต์', frequency: 'regular' },
            { id: 'bn-bp7-2', name: 'Digital Marketing', category: 'ไอที/การตลาด', description: 'SEO + Google Ads สำหรับเว็บบริษัท', frequency: 'regular' },
        ],
        trustLevel: 4,
        rating: 4.8,
        reviewCount: 44,
        dealsCompleted: 67,
        responseRate: 94,
        avgResponseTime: '1 ชั่วโมง',
        portfolioImages: [],
        contactPhone: '085-678-9012',
        contactEmail: 'contact@itsolutionpro.co.th',
        lineId: '@itsolutionpro',
        website: 'www.itsolutionpro.co.th',
        verified: true,
        memberSince: '2022-12-01',
        matchPowerScore: 88,
    },
    {
        id: 'bp-8',
        userId: 'user-9',
        businessName: 'วัสดุก่อสร้าง เจริญทรัพย์',
        businessType: 'wholesale',
        categories: ['ก่อสร้าง/วัสดุ'],
        subCategories: ['ปูน', 'เหล็ก', 'อิฐ', 'สี', 'กระเบื้อง'],
        province: 'ปทุมธานี',
        district: 'คลองหลวง',
        description: 'ขายส่งวัสดุก่อสร้างทุกชนิด สินค้ามี Stock พร้อมจัดส่ง ราคา โรงงาน',
        products: [
            { id: 'p-bp8-1', name: 'ปูนซีเมนต์ (ถุง)', description: 'ปูนผสม ปูนฉาบ ส่งขั้นต่ำ 100 ถุง', startingPrice: 145, moq: 100, leadTime: '1-2 วัน', tags: ['ปูน', 'ซีเมนต์'], images: [] },
            { id: 'p-bp8-2', name: 'เหล็กเส้น SD40', description: 'เหล็กเส้น 12mm 16mm ราคา/กก.', startingPrice: 25, moq: 1000, leadTime: '3-5 วัน', tags: ['เหล็ก', 'SD40'], images: [] },
        ],
        buyingNeeds: [
            { id: 'bn-bp8-1', name: 'รถขนส่งวัสดุ', category: 'ขนส่ง', description: 'รถ 6 ล้อ 10 ล้อ ขนวัสดุก่อสร้าง', frequency: 'regular' },
            { id: 'bn-bp8-2', name: 'เว็บไซต์และแคตตาล็อกออนไลน์', category: 'ไอที/เว็บ', description: 'เว็บ E-catalog ราคาสินค้า อัปเดตได้เอง', frequency: 'onetime' },
        ],
        trustLevel: 3,
        rating: 4.5,
        reviewCount: 203,
        dealsCompleted: 567,
        responseRate: 90,
        avgResponseTime: '2 ชั่วโมง',
        portfolioImages: [],
        contactPhone: '02-901-2345',
        contactEmail: 'chareon.material@gmail.com',
        lineId: '@chareonsap',
        website: '',
        verified: true,
        memberSince: '2023-07-01',
        matchPowerScore: 74,
    },
];

// ==================== RFQS ====================

export const RFQS: RFQ[] = [
    {
        id: 'rfq-1',
        buyerId: 'bp-3',
        buyerName: 'ABC Catering & Events',
        title: 'ต้องการเว็บไซต์ใหม่ พร้อม SEO และดูแล Facebook',
        category: 'ไอที/เว็บไซต์',
        type: 'service',
        quantity: 1,
        unit: 'งาน',
        budgetMin: 20000,
        budgetMax: 50000,
        deadline: '2026-03-15',
        requirements: 'ต้องการเว็บไซต์ใหม่สำหรับธุรกิจ Catering รองรับมือถือ มีระบบแจ้งราคาออนไลน์ ดู Portfolio งาน และติดต่อสอบถาม พร้อม SEO เพื่อให้ติดหน้า 1 Google และดูแล Facebook Page รายเดือน',
        supplierQualifications: {
            minTrustLevel: 2,
            mustHavePortfolio: false,
            minDealsCompleted: 5,
            sameProvince: false,
        },
        area: 'กรุงเทพมหานคร',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 3,
        matchedSellers: 12,
        createdAt: '2026-02-15',
        expiresAt: '2026-03-01',
    },
    {
        id: 'rfq-2',
        buyerId: 'bp-5',
        buyerName: 'Fashion Plus โรงงานเสื้อผ้า',
        title: 'ต้องการเว็บไซต์ E-commerce สำหรับ B2B สั่งซื้อออนไลน์',
        category: 'ไอที/เว็บไซต์',
        type: 'service',
        quantity: 1,
        unit: 'งาน',
        budgetMin: 35000,
        budgetMax: 80000,
        deadline: '2026-04-01',
        requirements: 'ต้องการระบบ E-commerce สำหรับลูกค้า B2B สามารถดูแคตตาล็อกสินค้า เลือกขนาด สี จำนวน และสั่งซื้อได้ออนไลน์ มีระบบ Login สำหรับลูกค้า ดูประวัติการสั่งซื้อ',
        supplierQualifications: {
            minTrustLevel: 2,
            mustHavePortfolio: true,
            minDealsCompleted: 10,
            sameProvince: false,
        },
        area: 'ทั่วประเทศ',
        attachments: [],
        visibility: 'verified_only',
        status: 'open',
        proposalCount: 5,
        matchedSellers: 8,
        createdAt: '2026-02-14',
        expiresAt: '2026-03-05',
    },
    {
        id: 'rfq-3',
        buyerId: 'bp-8',
        buyerName: 'วัสดุก่อสร้าง เจริญทรัพย์',
        title: 'ต้องการเว็บ E-catalog แสดงสินค้าก่อสร้าง อัปเดตได้เอง',
        category: 'ไอที/เว็บไซต์',
        type: 'service',
        quantity: 1,
        unit: 'งาน',
        budgetMin: 15000,
        budgetMax: 40000,
        deadline: '2026-03-30',
        requirements: 'เว็บไซต์สำหรับแสดงสินค้าวัสดุก่อสร้าง มีระบบ Admin อัปเดตราคาและสินค้าได้เอง ค้นหาสินค้าได้ มีระบบสอบถามราคา',
        supplierQualifications: {
            minTrustLevel: 2,
            mustHavePortfolio: false,
            minDealsCompleted: 3,
            sameProvince: false,
        },
        area: 'กรุงเทพมหานคร/ปริมณฑล',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 2,
        matchedSellers: 15,
        createdAt: '2026-02-16',
        expiresAt: '2026-03-08',
    },
    {
        id: 'rfq-4',
        buyerId: 'bp-7',
        buyerName: 'IT Solution Pro',
        title: 'ต้องการ SEO + Google Ads สำหรับเว็บไซต์บริษัท IT',
        category: 'Digital Marketing',
        type: 'service',
        quantity: 1,
        unit: 'เดือน',
        budgetMin: 10000,
        budgetMax: 25000,
        deadline: '2026-03-20',
        requirements: 'ต้องการทีมดูแล SEO เพิ่มอันดับ Keyword เช่น "พัฒนาแอป" "ซอฟต์แวร์ SME" และจัดการ Google Ads งบ 15,000/เดือน Report ทุกเดือน',
        supplierQualifications: {
            minTrustLevel: 2,
            mustHavePortfolio: true,
            minDealsCompleted: 5,
            sameProvince: false,
        },
        area: 'กรุงเทพมหานคร',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 7,
        matchedSellers: 20,
        createdAt: '2026-02-13',
        expiresAt: '2026-03-01',
    },
    {
        id: 'rfq-5',
        buyerId: 'bp-4',
        buyerName: 'สำนักงานบัญชี ธนกิจ',
        title: 'ต้องการเว็บไซต์สำนักงานบัญชี ดูเป็นมืออาชีพ SEO ดี',
        category: 'ไอที/เว็บไซต์',
        type: 'service',
        quantity: 1,
        unit: 'งาน',
        budgetMin: 12000,
        budgetMax: 30000,
        deadline: '2026-03-25',
        requirements: 'เว็บไซต์สำหรับสำนักงานบัญชี ดูเป็นมืออาชีพ น่าเชื่อถือ มีหน้าบริการ ราคา บทความ และติดต่อ SEO ให้ติด Google',
        supplierQualifications: {
            minTrustLevel: 1,
            mustHavePortfolio: false,
            minDealsCompleted: 3,
            sameProvince: true,
        },
        area: 'กรุงเทพมหานคร',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 4,
        matchedSellers: 18,
        createdAt: '2026-02-17',
        expiresAt: '2026-03-10',
    },
    {
        id: 'rfq-6',
        buyerId: 'bp-1',
        buyerName: 'โรงพิมพ์ศรีสยาม',
        title: 'ต้องการพิมพ์นามบัตรพรีเมี่ยม สำหรับทีม Sales 50 ชุด',
        category: 'สิ่งพิมพ์',
        type: 'product',
        quantity: 50,
        unit: 'ชุด',
        budgetMin: 5000,
        budgetMax: 15000,
        deadline: '2026-03-05',
        requirements: 'นามบัตรพรีเมี่ยม กระดาษหนา เคลือบ UV เยื้อ หรือฟอยล์ทอง สำหรับฝ่าย Sales จำนวน 50 ชุด ชุดละ 100 ใบ',
        supplierQualifications: {
            minTrustLevel: 1,
            mustHavePortfolio: false,
            minDealsCompleted: 5,
            sameProvince: false,
        },
        area: 'กรุงเทพมหานคร',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 8,
        matchedSellers: 25,
        createdAt: '2026-02-12',
        expiresAt: '2026-02-25',
    },
    {
        id: 'rfq-7',
        buyerId: 'bp-6',
        buyerName: 'ส่งด่วน Express Logistics',
        title: 'ต้องการระบบ GPS Tracking สำหรับรถขนส่ง 30 คัน',
        category: 'ไอที/Software',
        type: 'product',
        quantity: 30,
        unit: 'คัน',
        budgetMin: 50000,
        budgetMax: 150000,
        deadline: '2026-04-15',
        requirements: 'ระบบ GPS Tracking แบบ Real-time สำหรับรถขนส่ง 30 คัน มี App บน iOS/Android ดูเส้นทาง ประวัติการวิ่ง ควบคุมความเร็ว Report ประจำวัน',
        supplierQualifications: {
            minTrustLevel: 2,
            mustHavePortfolio: true,
            minDealsCompleted: 5,
            sameProvince: false,
        },
        area: 'ทั่วประเทศ',
        attachments: [],
        visibility: 'verified_only',
        status: 'open',
        proposalCount: 3,
        matchedSellers: 5,
        createdAt: '2026-02-10',
        expiresAt: '2026-03-15',
    },
    {
        id: 'rfq-8',
        buyerId: 'bp-2',
        buyerName: 'ร้านป้ายไฟ LED สมชาย',
        title: 'ต้องการนักออกแบบกราฟิก Freelance สำหรับ Artwork ป้ายลูกค้า',
        category: 'กราฟิก/ดีไซน์',
        type: 'service',
        quantity: 20,
        unit: 'งาน/เดือน',
        budgetMin: 8000,
        budgetMax: 20000,
        deadline: '2026-03-01',
        requirements: 'นักออกแบบกราฟิก Freelance รับออกแบบ Artwork ป้ายตามที่ลูกค้าต้องการ ประมาณ 20 งาน/เดือน ใช้ Illustrator/Photoshop ส่งไฟล์ภายใน 24 ชั่วโมง',
        supplierQualifications: {
            minTrustLevel: 1,
            mustHavePortfolio: true,
            minDealsCompleted: 0,
            sameProvince: false,
        },
        area: 'ทำงานออนไลน์',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 11,
        matchedSellers: 30,
        createdAt: '2026-02-11',
        expiresAt: '2026-02-28',
    },
    {
        id: 'rfq-9',
        buyerId: 'bp-8',
        buyerName: 'วัสดุก่อสร้าง เจริญทรัพย์',
        title: 'ต้องการรถ 6 ล้อ + 10 ล้อ ขนวัสดุก่อสร้าง รายสัปดาห์',
        category: 'ขนส่ง/โลจิสติกส์',
        type: 'service',
        quantity: 8,
        unit: 'เที่ยว/สัปดาห์',
        budgetMin: 25000,
        budgetMax: 60000,
        deadline: '2026-03-01',
        requirements: 'ต้องการรถ 6 ล้อ / 10 ล้อ ประจำสัปดาห์ ขนวัสดุก่อสร้างจาก ปทุมธานี ไปส่งในกรุงเทพฯ และปริมณฑล สัปดาห์ละ 6-8 เที่ยว',
        supplierQualifications: {
            minTrustLevel: 2,
            mustHavePortfolio: false,
            minDealsCompleted: 20,
            sameProvince: false,
        },
        area: 'กรุงเทพฯ/ปทุมธานี/ปริมณฑล',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 6,
        matchedSellers: 9,
        createdAt: '2026-02-08',
        expiresAt: '2026-02-25',
    },
    {
        id: 'rfq-10',
        buyerId: 'bp-5',
        buyerName: 'Fashion Plus โรงงานเสื้อผ้า',
        title: 'ต้องการช่างภาพถ่ายแคตตาล็อกเสื้อผ้า Lookbook ฤดูกาลใหม่',
        category: 'ถ่ายภาพ/วิดีโอ',
        type: 'service',
        quantity: 1,
        unit: 'งาน',
        budgetMin: 15000,
        budgetMax: 40000,
        deadline: '2026-03-20',
        requirements: 'ต้องการช่างภาพมืออาชีพถ่าย Lookbook เสื้อผ้า Collection ใหม่ ประมาณ 30-40 ชุด ถ่าย Studio และ Outdoor โพสต์แปรรูปเรียบร้อย ส่ง Digital File',
        supplierQualifications: {
            minTrustLevel: 1,
            mustHavePortfolio: true,
            minDealsCompleted: 5,
            sameProvince: false,
        },
        area: 'กรุงเทพมหานคร/สมุทรปราการ',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 9,
        matchedSellers: 14,
        createdAt: '2026-02-13',
        expiresAt: '2026-03-01',
    },
];

// ==================== PROPOSALS ====================

export const PROPOSALS: Proposal[] = [
    // Proposals WE SENT
    {
        id: 'prop-1',
        rfqId: 'rfq-1',
        sellerId: 'bp-my',
        sellerName: 'LeadSpark Digital',
        sellerTrustLevel: 3,
        sellerRating: 4.6,
        price: 35000,
        unit: 'งาน',
        leadTime: '21 วัน',
        description: 'เสนอแพ็กเกจครบ: เว็บไซต์ WordPress SEO-friendly + ดูแล Facebook Page 3 เดือน รวมค่าโดเมน/โฮสติ้ง 1 ปี',
        attachments: [],
        status: 'viewed',
        matchScore: 92,
        createdAt: '2026-02-16',
    },
    {
        id: 'prop-2',
        rfqId: 'rfq-4',
        sellerId: 'bp-my',
        sellerName: 'LeadSpark Digital',
        sellerTrustLevel: 3,
        sellerRating: 4.6,
        price: 15000,
        unit: 'เดือน',
        leadTime: 'เริ่มได้ทันที',
        description: 'SEO รายเดือน: On-page + Off-page 10 Keyword เป้าหมาย + Google Ads บัญชีงบ 15,000 บ./เดือน Report สรุปทุกวันที่ 1',
        attachments: [],
        status: 'shortlisted',
        matchScore: 88,
        createdAt: '2026-02-14',
    },
    {
        id: 'prop-3',
        rfqId: 'rfq-5',
        sellerId: 'bp-my',
        sellerName: 'LeadSpark Digital',
        sellerTrustLevel: 3,
        sellerRating: 4.6,
        price: 18000,
        unit: 'งาน',
        leadTime: '14 วัน',
        description: 'เว็บไซต์สำนักงานบัญชีมืออาชีพ WordPress มีหน้าบริการ บทความ SEO และระบบ Contact Form พร้อมค่าโฮสติ้ง 1 ปี',
        attachments: [],
        status: 'sent',
        matchScore: 85,
        createdAt: '2026-02-18',
    },

    // Proposals WE RECEIVED
    {
        id: 'prop-4',
        rfqId: 'rfq-my-1',
        sellerId: 'bp-1',
        sellerName: 'โรงพิมพ์ศรีสยาม',
        sellerTrustLevel: 3,
        sellerRating: 4.8,
        price: 650,
        unit: 'ชุด (100 ใบ)',
        leadTime: '5 วัน',
        description: 'นามบัตรพรีเมี่ยม กระดาษ 350g เคลือบ UV นูน ดีไซน์สวย ราคา 650 บ./ชุด 50 ชุด รวม 32,500 บาท',
        attachments: [],
        status: 'viewed',
        matchScore: 79,
        createdAt: '2026-02-15',
    },
    {
        id: 'prop-5',
        rfqId: 'rfq-my-2',
        sellerId: 'bp-7',
        sellerName: 'IT Solution Pro',
        sellerTrustLevel: 4,
        sellerRating: 4.8,
        price: 45000,
        unit: 'งาน',
        leadTime: '30 วัน',
        description: 'พัฒนาเว็บ + ระบบ Blog ด้วย Next.js SEO-Optimized มือถือ รวดเร็ว Admin Panel จัดการเองได้ รองรับ 10,000 ผู้เข้าชม/วัน',
        attachments: [],
        status: 'shortlisted',
        matchScore: 83,
        createdAt: '2026-02-16',
    },
    {
        id: 'prop-6',
        rfqId: 'rfq-my-2',
        sellerId: 'bp-3',
        sellerName: 'ABC Digital Agency',
        sellerTrustLevel: 2,
        sellerRating: 4.2,
        price: 28000,
        unit: 'งาน',
        leadTime: '21 วัน',
        description: 'เว็บไซต์ WordPress ปรับแต่ง Theme Premium + ตั้งค่า SEO พื้นฐาน ฝึกใช้งาน 2 ชั่วโมง',
        attachments: [],
        status: 'sent',
        matchScore: 68,
        createdAt: '2026-02-17',
    },
];

// ==================== MARKETPLACE DEALS ====================

export const MARKETPLACE_DEALS: MarketplaceDeal[] = [
    {
        id: 'md-1',
        rfqId: 'rfq-old-1',
        proposalId: 'prop-old-1',
        buyerId: 'bp-prev-1',
        sellerId: 'bp-my',
        title: 'เว็บไซต์ + SEO สำหรับ Coffee Shop The Brew Lab',
        value: 28000,
        status: 'completed',
        buyerReview: {
            rating: 5,
            comment: 'งานดีมาก ส่งตรงเวลา ติดต่อง่าย แนะนำเลย! เว็บไซต์สวยกว่าที่คิด',
            createdAt: '2026-01-20',
        },
        sellerReview: {
            rating: 5,
            comment: 'ลูกค้าดูแลง่าย Feedback ชัดเจน จ่ายเงินตรงเวลา ยินดีรับงานอีก',
            createdAt: '2026-01-22',
        },
        completedAt: '2026-01-18',
    },
    {
        id: 'md-2',
        rfqId: 'rfq-4',
        proposalId: 'prop-2',
        buyerId: 'bp-7',
        sellerId: 'bp-my',
        title: 'SEO + Google Ads สำหรับ IT Solution Pro',
        value: 15000,
        status: 'agreed',
        completedAt: undefined,
    },
    {
        id: 'md-3',
        rfqId: 'rfq-1',
        proposalId: 'prop-1',
        buyerId: 'bp-3',
        sellerId: 'bp-my',
        title: 'เว็บไซต์ + ดูแล Facebook สำหรับ ABC Catering',
        value: 35000,
        status: 'negotiating',
        completedAt: undefined,
    },
];

// ==================== MY RFQS (user posted) ====================

export const MY_RFQS: RFQ[] = [
    {
        id: 'rfq-my-1',
        buyerId: 'bp-my',
        buyerName: 'LeadSpark Digital',
        title: 'ต้องการพิมพ์นามบัตร Premium สำหรับทีม 50 ชุด',
        category: 'สิ่งพิมพ์',
        type: 'product',
        quantity: 50,
        unit: 'ชุด',
        budgetMin: 20000,
        budgetMax: 40000,
        deadline: '2026-03-10',
        requirements: 'นามบัตรพรีเมี่ยม ลักษณะ Black & Gold กระดาษหนา 350g เคลือบ UV นูน หรือ Soft Touch Foil ทอง สำหรับทีม 50 คน',
        supplierQualifications: {
            minTrustLevel: 2,
            mustHavePortfolio: true,
            minDealsCompleted: 10,
            sameProvince: false,
        },
        area: 'กรุงเทพมหานคร',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 2,
        matchedSellers: 8,
        createdAt: '2026-02-14',
        expiresAt: '2026-03-01',
    },
    {
        id: 'rfq-my-2',
        buyerId: 'bp-my',
        buyerName: 'LeadSpark Digital',
        title: 'ต้องการนักเขียน Content SEO ภาษาไทย (ไอที/การตลาด) รายเดือน',
        category: 'คอนเทนต์',
        type: 'service',
        quantity: 8,
        unit: 'บทความ/เดือน',
        budgetMin: 8000,
        budgetMax: 16000,
        deadline: '2026-03-05',
        requirements: 'ต้องการนักเขียนบทความ SEO เรื่องไอที Digital Marketing และธุรกิจ SME บทความละ 1,000-1,500 คำ ส่งทุกๆ 3-4 วัน',
        supplierQualifications: {
            minTrustLevel: 1,
            mustHavePortfolio: true,
            minDealsCompleted: 0,
            sameProvince: false,
        },
        area: 'ทำงานออนไลน์',
        attachments: [],
        visibility: 'everyone',
        status: 'open',
        proposalCount: 3,
        matchedSellers: 22,
        createdAt: '2026-02-16',
        expiresAt: '2026-03-02',
    },
];
